import { addIcons } from 'ionicons';
import {
  arrowForwardOutline,
  bookmarkOutline,
  cameraOutline,
  chatbubbleOutline,
  chatbubbleEllipsesOutline,
  chatbubblesOutline,
  closeOutline,
  createOutline,
  cloudOfflineOutline,
  colorWandOutline,
  documentTextOutline,
  ellipsisVerticalOutline,
  eyeOutline,
  flaskOutline,
  imagesOutline,
  layersOutline,
  listOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  personOutline,
  planetOutline,
  readerOutline,
  refreshOutline,
  searchOutline,
  sendOutline,
  settingsOutline,
  sparklesOutline,
  warningOutline,
} from 'ionicons/icons';

/** Call once at bootstrap so `ion-icon` works on lazy-loaded routes too. */
export function registerAppIonIcons(): void {
  addIcons({
    arrowForwardOutline,
    chatbubblesOutline,
    chatbubbleOutline,
    peopleOutline,
    personAddOutline,
    settingsOutline,
    personCircleOutline,
    sparklesOutline,
    layersOutline,
    colorWandOutline,
    planetOutline,
    documentTextOutline,
    readerOutline,
    listOutline,
    bookmarkOutline,
    cameraOutline,
    refreshOutline,
    cloudOfflineOutline,
    warningOutline,
    personOutline,
    sendOutline,
    chatbubbleEllipsesOutline,
    searchOutline,
    createOutline,
    ellipsisVerticalOutline,
    eyeOutline,
    imagesOutline,
    flaskOutline,
  });
}
